Project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from pythonprogrammer import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home,name='home'),
    url(r'^pythonprogrammer/', include('pythonprogrammer.urls')),

    #password reset urls
    url(r'^password-reset/$',auth_views.PasswordResetView.as_view(template_name='pythonprogrammer/password_reset.html'),name='password_reset'),
    url(r'^password-reset-done/$',auth_views.PasswordResetDoneView.as_view(template_name='pythonprogrammer/password_reset_done.html'),name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9a-zA-Z]+)-(?P<token>.+)/$',auth_views.PasswordResetConfirmView.as_view(template_name='pythonprogrammer/password_reset_confirm.html'),name='password_reset_confirm'),
    url(r'^password-reset-complete/$',auth_views.PasswordResetCompleteView.as_view(template_name='pythonprogrammer/password_reset_complete.html'),name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pythonprogrammer/urls.py
from django.conf.urls import url
from pythonprogrammer import views


app_name = 'pythonprogrammer'

urlpatterns = [
    url(r'^details/', views.details,name='details'),
    url(r'^libraries/', views.libraries,name='libraries'),
    url(r'^signup/', views.signup,name='signup'),
    url(r'^login/', views.user_login,name='user_login'),
    url(r'^user_logout/', views.user_logout,name='user_logout'),
    url(r'^profile/', views.profile,name='profile'),
    url(r'^update_profile/', views.update_profile,name='update_profile'),
 ]

pythonprogrammer/models.py
from django.db import models

# Create your models here.

pythonprogrammer/forms.py
from django import forms
from django.contrib.auth.models import User
import re
from django.core.validators import validate_email
from django.contrib.auth.forms import UserChangeForm

class Signup_Form(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Username..'}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter First Name..'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Last Name..'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Enter Email..'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Password..'}))
	cnfpassword = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Password Again..'}))


	class Meta:
		model = User
		fields = ['username','first_name','last_name','email','password']

	def clean_username(self):
		username = self.cleaned_data['username']
		if len(username) >= 6 and len(username) <= 12:
			try:
				User.objects.get(username=username)
				raise forms.ValidationError('username already taken')
			except:
				regex = '^[a-z](?=.*[0-9][0-9][0-9])[a-z0-9]+$'
				match = re.fullmatch(regex,username)
				if match != None:
					return username
				else:
					raise forms.ValidationError('invalid username')
		else:
			raise forms.ValidationError('invalid username')

	def clean_first_name(self):
		first_name = self.cleaned_data['first_name']
		if first_name.isalpha():
			return first_name
		else:
			raise forms.ValidationError('a good name only contain alphabate')

	def clean_last_name(self):
		last_name = self.cleaned_data['last_name']
		if last_name.isalpha():
			return last_name
		else:
			raise forms.ValidationError('a good name only contain alphabate')

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			valid = validate_email(email)
		except:
			raise forms.ValidationError('Invalid Email')
		try:
			match = User.objects.get(email=email)
		except:
			return email
			raise forms.ValidationError('Email Already Exist')

	def clean_password(self):
		password = self.cleaned_data['password']
		regex = '^(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-z0-9!@#$%^&*]{8,15}$'
		match = re.fullmatch(regex,password)
		if match != None:
			return password
		else:
			raise forms.ValidationError('Invalid password')

	def clean_cnfpassword(self):
		password = self.cleaned_data.get('password')
		cnfpassword = self.cleaned_data['cnfpassword']
		if cnfpassword == password:
			return cnfpassword
		else:
			raise forms.ValidationError('password not matched')

class Login_Form(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Username..'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Password..'}))

	class Meta:
		model = User
		fields = ['username','password']

class Update_Profile_Form(UserChangeForm):

	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Username..'}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter First Name..'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Last Name..'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Enter Email..'}))

	class Meta:
		model = User
		fields = ['username','first_name','last_name','email','password']

	def clean_username(self):
		username = self.cleaned_data['username']
		if len(username) >= 6 and len(username) <= 12:
			try:
				User.objects.get(username=username)
				raise forms.ValidationError('username already taken')
			except:
				regex = '^[a-z](?=.*[0-9][0-9][0-9])[a-z0-9]+$'
				match = re.fullmatch(regex,username)
				if match != None:
					return username
				else:
					raise forms.ValidationError('invalid username')
		else:
			raise forms.ValidationError('invalid username')

	def clean_first_name(self):
		first_name = self.cleaned_data['first_name']
		if first_name.isalpha():
			return first_name
		else:
			raise forms.ValidationError('a good name only contain alphabate')

	def clean_last_name(self):
		last_name = self.cleaned_data['last_name']
		if last_name.isalpha():
			return last_name
		else:
			raise forms.ValidationError('a good name only contain alphabate')

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			valid = validate_email(email)
		except:
			raise forms.ValidationError('Invalid Email')
		try:
			match = User.objects.get(email=email)
		except:
			return email
			raise forms.ValidationError('Email Already Exist')

pythonprogrammer/views.py
from django.shortcuts import render,redirect
from .forms import Signup_Form,Login_Form,Update_Profile_Form
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

def home(request):
	return render(request,'pythonprogrammer/home.html')

def details(request):
	return render(request,'pythonprogrammer/details.html')

def libraries(request):
	return render(request,'pythonprogrammer/libraries.html')

def signup(request):
    if request.method == 'POST':
        form = Signup_Form(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()
            messages.success(request,'Signup Successfull Thank You!!')
            return redirect('/pythonprogrammer/login')
        else:
            return render(request,'pythonprogrammer/signup.html',{'form':form})
    else:
        form = Signup_Form()
        context = {'form':form}
        return render(request,'pythonprogrammer/signup.html',context)

def user_login(request):
	form = Login_Form()
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)
				return redirect('home')
			else:
				return redirect('/pythonprogrammer/login',{'form':form})
		else:
			messages.warning(request,'Wrong Details!!')
			return redirect('/pythonprogrammer/login',{'form':form})
	else:
		return render(request,'pythonprogrammer/login.html',{'form':form})

@login_required
def user_logout(request):
	logout(request)
	return redirect('home')

def profile(request):
	user = request.user
	return render(request,'pythonprogrammer/profile.html',{'user':user})

def update_profile(request):
	form = Update_Profile_Form(instance=request.user)
	if request.method == 'POST':
		form = Update_Profile_Form(request.POST,instance=request.user)
		if form.is_valid():
			form.save()
			messages.success(request,'Your profile has been updated!!')
			return redirect('/pythonprogrammer/profile')
		else:
			return render(request,'pythonprogrammer/update_profile.html',{'form':form})
	else:
		return render(request,'pythonprogrammer/update_profile.html',{'form':form})
		

templates/pythonprogrammer/password_reset.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<!-- TITLE BAR -->
	<title>Reset Password</title>
	<link rel="shortcut icon" type="image/png" href="{%static 'images/favicon.png' %}">

	<!-- META DATA -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Talib Qureshi">

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <!-- CDN -->
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Bitter|Germania+One" rel="stylesheet">
	<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css'>
  <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">

  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
</head>

<body class="animated slideInUp">
	<nav class="navbar navbar-expand-lg navbar-dark sticky-top">
    <a class="navbar-brand" href="#">
       <img src="{%static 'images/favicon.png' %}" width="50" height="50" alt="PP"><span class='site_name'>PythonProgrammer</span>
    </a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 	aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
    	</button>
    	<!-- NAV BAR-->
    	<div class="collapse navbar-collapse" id="navbarSupportedContent">
      		<ul class="navbar-nav ml-auto">
        		<li class="nav-item">
          			<a class="nav-link" href="{%url 'home' %}"><b>Home</b></a>
        		</li>
            <li class="nav-item">
          			<a class="nav-link" href="{%url 'pythonprogrammer:libraries' %}"><b>Libraries</b></a>
        		</li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:signup' %}"><b>Signup</b></a>
            </li>
          	<li class="nav-item">
            		<a class="nav-link" href="{%url 'pythonprogrammer:user_login' %}"><b>Login</b></a>
          	</li>
      		</ul>
      	</div>
	</nav>

	<div class="container">
		<div class='jumbotron'>
    	<div class="row">
				<div class='col-lg-3 col-md-3 col-sm-0 col-xs-0'>
				</div>

				<div class='col-lg-6 col-md-6 col-sm-12 col-xs-12'>
          <h5 class="text-center text-muted">Enter your E-mail to reset password</h5>
          <br>
          <h2 class="text-center">Reset Password</h2>
          <br>
					<form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="email"><b>Email:</b></label>
              <input type="email" name="email" class="form-control" placeholder="Enter Email..">
            </div>
            <button type="submit" name="reset_password" class="btn btn-info navbtn">Request Reset Password</button>
          </form>
        </div>

				<div class='col-lg-3 col-md-3 col-sm-0 col-xs-0'>
				</div>
			</div>
		</div>
	</div>

  <!-- Footer -->
	<div class="container-fluid footer">
      <div class="row">
        <div class='col-lg-6 col-md-6'>
            <h4 style='text-shadow: 2px 2px #233237; text-align:center; margin-top: 3px;'>Contact Us</h4>
            <div class="social_icon">
              <a href="#" title="Facebook" class='icons'><i class='fa fa-facebook'></i></a>
              <a href="#" title="Instagram" class='icons'><i class='fa fa-instagram'></i></a>
              <a href="#" title="WhatsApp" class='icons'><i class='fa fa-whatsapp'></i></a>
              <a href="#" title="Twitter" class='icons'><i class='fa fa-twitter'></i></a>
              <a href="#" title='Google' class='icons'><i class='fa fa-google'></i></a>
            </div><br>
            <div class='contact_info'>
              <h6><i class="fa fa-map"></i> Address -<span style="font-weight: 300;"> 10 Satya Sai Colony Nahar Sayyad Road Mandsaur M.P 458001</span></h6>
              <h6><i class="fa fa-phone"></i> Mobile -<span style="font-weight: 300;"> 07987051968</span></h6>
              <h6><i class="fa fa-envelope"></i> Email -<span style="font-weight: 300;"> talibhqureshi@gmail.com</span></h6>
              </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <form class="form-inline footer_search">
                <input class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search">
                <button class="btn btn-success my-2 my-sm-0 navbtn" type="submit" id='search_btn'><b>Search</b></button>
            </form>
          </div>
      </div>
      <br>
      <div style='text-align: center; font-size: 14px; font-weight: 400;'>&copy Powered By PythonProgrammer.com</div>
    </div>

</body>
</html>

templates/pythonprogrammer/password_reset_complete.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<!-- TITLE BAR -->
	<title>Reset Password</title>
	<link rel="shortcut icon" type="image/png" href="{%static 'images/favicon.png' %}">

	<!-- META DATA -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Talib Qureshi">

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <!-- CDN -->
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Bitter|Germania+One" rel="stylesheet">
	<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css'>
  <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">

  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
</head>

<body class="animated slideInUp">
  <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
    <a class="navbar-brand" href="#">
       <img src="{%static 'images/favicon.png' %}" width="50" height="50" alt="PP"><span class='site_name'>PythonProgrammer</span>
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"  aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- NAV BAR-->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'home' %}"><b>Home</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:libraries' %}"><b>Libraries</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:signup' %}"><b>Signup</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:user_login' %}"><b>Login</b></a>
            </li>
          </ul>
        </div>
  </nav>

	<div class="container">
    <div class='jumbotron'>
			<div class="alert alert-info">
        Your Password is Set
      </div>
      <br>
      <a href="{%url 'pythonprogrammer:user_login' %}" class="btn btn-info navbtn">Login</a>

		</div>
	</div>

  <!-- Footer -->
	<div class="container-fluid footer">
      <div class="row">
        <div class='col-lg-6 col-md-6'>
            <h4 style='text-shadow: 2px 2px #233237; text-align:center; margin-top: 3px;'>Contact Us</h4>
            <div class="social_icon">
              <a href="#" title="Facebook" class='icons'><i class='fa fa-facebook'></i></a>
              <a href="#" title="Instagram" class='icons'><i class='fa fa-instagram'></i></a>
              <a href="#" title="WhatsApp" class='icons'><i class='fa fa-whatsapp'></i></a>
              <a href="#" title="Twitter" class='icons'><i class='fa fa-twitter'></i></a>
              <a href="#" title='Google' class='icons'><i class='fa fa-google'></i></a>
            </div><br>
            <div class='contact_info'>
              <h6><i class="fa fa-map"></i> Address -<span style="font-weight: 300;"> 10 Satya Sai Colony Nahar Sayyad Road Mandsaur M.P 458001</span></h6>
              <h6><i class="fa fa-phone"></i> Mobile -<span style="font-weight: 300;"> 07987051968</span></h6>
              <h6><i class="fa fa-envelope"></i> Email -<span style="font-weight: 300;"> talibhqureshi@gmail.com</span></h6>
              </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <form class="form-inline footer_search">
                <input class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search">
                <button class="btn btn-success my-2 my-sm-0 navbtn" type="submit" id='search_btn'><b>Search</b></button>
            </form>
          </div>
      </div>
      <br>
      <div style='text-align: center; font-size: 14px; font-weight: 400;'>&copy Powered By PythonProgrammer.com</div>
    </div>

</body>
</html>

templates/pythonprogrammer/password_reset_confirm.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<!-- TITLE BAR -->
	<title>Reset Password</title>
	<link rel="shortcut icon" type="image/png" href="{%static 'images/favicon.png' %}">

	<!-- META DATA -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Talib Qureshi">

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <!-- CDN -->
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Bitter|Germania+One" rel="stylesheet">
	<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css'>
  <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">

  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
</head>

<body class="animated slideInUp">
  <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
    <a class="navbar-brand" href="#">
       <img src="{%static 'images/favicon.png' %}" width="50" height="50" alt="PP"><span class='site_name'>PythonProgrammer</span>
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"  aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- NAV BAR-->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'home' %}"><b>Home</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:libraries' %}"><b>Libraries</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:signup' %}"><b>Signup</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:user_login' %}"><b>Login</b></a>
            </li>
          </ul>
        </div>
  </nav>

	<div class="container">
    <div class='jumbotron'>
			<div class="row">
        <div class='col-lg-3 col-md-3 col-sm-0 col-xs-0'>
        </div>

        <div class='col-lg-6 col-md-6 col-sm-12 col-xs-12'>
          <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-info navbtn">Reset Password</button>
          </form>
        </div>

        <div class='col-lg-3 col-md-3 col-sm-0 col-xs-0'>
        </div>
      </div>

		</div>
	</div>

  <!-- Footer -->
	<div class="container-fluid footer">
      <div class="row">
        <div class='col-lg-6 col-md-6'>
            <h4 style='text-shadow: 2px 2px #233237; text-align:center; margin-top: 3px;'>Contact Us</h4>
            <div class="social_icon">
              <a href="#" title="Facebook" class='icons'><i class='fa fa-facebook'></i></a>
              <a href="#" title="Instagram" class='icons'><i class='fa fa-instagram'></i></a>
              <a href="#" title="WhatsApp" class='icons'><i class='fa fa-whatsapp'></i></a>
              <a href="#" title="Twitter" class='icons'><i class='fa fa-twitter'></i></a>
              <a href="#" title='Google' class='icons'><i class='fa fa-google'></i></a>
            </div><br>
            <div class='contact_info'>
              <h6><i class="fa fa-map"></i> Address -<span style="font-weight: 300;"> 10 Satya Sai Colony Nahar Sayyad Road Mandsaur M.P 458001</span></h6>
              <h6><i class="fa fa-phone"></i> Mobile -<span style="font-weight: 300;"> 07987051968</span></h6>
              <h6><i class="fa fa-envelope"></i> Email -<span style="font-weight: 300;"> talibhqureshi@gmail.com</span></h6>
              </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <form class="form-inline footer_search">
                <input class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search">
                <button class="btn btn-success my-2 my-sm-0 navbtn" type="submit" id='search_btn'><b>Search</b></button>
            </form>
          </div>
      </div>
      <br>
      <div style='text-align: center; font-size: 14px; font-weight: 400;'>&copy Powered By PythonProgrammer.com</div>
    </div>

</body>
</html>

templates/pythonprogrammer/password_reset_done.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<!-- TITLE BAR -->
	<title>Reset Password</title>
	<link rel="shortcut icon" type="image/png" href="{%static 'images/favicon.png' %}">

	<!-- META DATA -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Talib Qureshi">

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <!-- CDN -->
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Bitter|Germania+One" rel="stylesheet">
	<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css'>
  <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">

  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
</head>

<body class="animated slideInUp">
  <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
    <a class="navbar-brand" href="#">
       <img src="{%static 'images/favicon.png' %}" width="50" height="50" alt="PP"><span class='site_name'>PythonProgrammer</span>
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"  aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- NAV BAR-->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'home' %}"><b>Home</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:libraries' %}"><b>Libraries</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:signup' %}"><b>Signup</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'pythonprogrammer:user_login' %}"><b>Login</b></a>
            </li>
          </ul>
        </div>
  </nav>

	<div class="container">
    <div class='jumbotron'>
			<div class="alert alert-info">
        An Email has been sent with instructions to reset your password
      </div>
		</div>
	</div>

  <!-- Footer -->
	<div class="container-fluid footer">
      <div class="row">
        <div class='col-lg-6 col-md-6'>
            <h4 style='text-shadow: 2px 2px #233237; text-align:center; margin-top: 3px;'>Contact Us</h4>
            <div class="social_icon">
              <a href="#" title="Facebook" class='icons'><i class='fa fa-facebook'></i></a>
              <a href="#" title="Instagram" class='icons'><i class='fa fa-instagram'></i></a>
              <a href="#" title="WhatsApp" class='icons'><i class='fa fa-whatsapp'></i></a>
              <a href="#" title="Twitter" class='icons'><i class='fa fa-twitter'></i></a>
              <a href="#" title='Google' class='icons'><i class='fa fa-google'></i></a>
            </div><br>
            <div class='contact_info'>
              <h6><i class="fa fa-map"></i> Address -<span style="font-weight: 300;"> 10 Satya Sai Colony Nahar Sayyad Road Mandsaur M.P 458001</span></h6>
              <h6><i class="fa fa-phone"></i> Mobile -<span style="font-weight: 300;"> 07987051968</span></h6>
              <h6><i class="fa fa-envelope"></i> Email -<span style="font-weight: 300;"> talibhqureshi@gmail.com</span></h6>
              </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <form class="form-inline footer_search">
                <input class="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search">
                <button class="btn btn-success my-2 my-sm-0 navbtn" type="submit" id='search_btn'><b>Search</b></button>
            </form>
          </div>
      </div>
      <br>
      <div style='text-align: center; font-size: 14px; font-weight: 400;'>&copy Powered By PythonProgrammer.com</div>
    </div>

</body>
</html>